services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name=: ${CONTAINER_NAME}
    networks:
      - npm_containers
    ports:
      - ${WEBPORT}:80
    environment:
      - TZ=${TZ}
    user: "${UUID}:${GUID}"
    labels:
      - homepage.group=${HOMEPAGE_SERVICE_GROUP}
      - homepage.name=${HOMEPAGE_SERVICE_NAME}
      - homepage.icon=filebrowser
      - homepage.href=${HOMEPAGE_URL}
      - homepage.description=${HOMEPAGE_DESCRIPTION}
      - homepage.widget.type=filebrowser
      - homepage.widget.url=${HOMEPAGE_URL}
      - homepage.widget.username=${HOMEPAGE_USERNAME}
      - homepage.widget.password=${HOMEPAGE_PASSWORD}
      - homepage.docker=true
    volumes:
      - ${VOLUMEROOT}:/srv:rw
      - ${VOLUMEROOT}/${CONTAINER_NAME}/database:/database:rw
      - ${VOLUMEROOT}/${CONTAINER_NAME}/config:/config:rw
    restart: unless-stopped
