services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    environment:
      - TZ=${TZ}                                                   # Time zone (i.e. America/Denver)
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}     # API token for reporting to Homepage (i.e. 9f3c2e7a4b8d1c6f5a2e9b7d4c1f8a6e3d7b2c9f1a4e6d8c3b7f2a9d5e1c4b8)
    lables:
      - homepage.group=${HOMEPAGE_SERVICE_GROUP}
      - homepage.name=${HOMEPAGE_SERVICE_NAME}
      - homepage.icon=watchtower
      - homepage.description=Watchtower Image Management
      - homepage.widget.type=watchtower
      - homepage.widget.url=${WATCHTOWER_URL}
      - homepage.widget.key=${WATCHTOWER_HTTP_API_TOKEN}
    ports:
      - "8080:8080"                               # External facing web port
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
